In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('/Users/melanyalegre/Documents/International Business/4th year/Data Analytics/Data Science/DS_assignment_data - Copy (1).csv')
df.head()

,UNIQUEID,DISBURSED_AMOUNT,ASSET_COST,LTV,BRANCH_ID,CURRENT_PINCODE_ID,DATE_OF_BIRTH,EMPLOYMENT_TYPE,DISBURSAL_DATE,MOBILENO_AVL_FLAG,...,SEC_SANCTIONED_AMOUNT,SEC_DISBURSED_AMOUNT,PRIMARY_INSTAL_AMT,SEC_INSTAL_AMT,NEW_ACCTS_IN_LAST_SIX_MONTHS,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,AVERAGE_ACCT_AGE,CREDIT_HISTORY_LENGTH,NO_OF_INQUIRIES,LOAN_DEFAULT
0,420825,50578,58400,89.55,67,1441,01/01/1984,Salaried,03/08/2018,1,...,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0
1,537409,47145,65550,73.23,67,1502,31/07/1985,Self employed,26/09/2018,1,...,0,0,1991,0,0,1,1yrs 11mon,1yrs 11mon,0,1
2,417566,53278,61360,89.63,67,1497,24/08/1985,Self employed,01/08/2018,1,...,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0
3,624493,57513,66113,88.48,67,1501,30/12/1993,Self employed,26/10/2018,1,...,0,0,31,0,0,0,0yrs 8mon,1yrs 3mon,1,1
4,539055,52378,60300,88.39,67,1495,09/12/1977,Self employed,26/09/2018,1,...,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,1,1

In [24]:
df = df.drop(columns=['UNIQUEID', 'BRANCH_ID', 'CURRENT_PINCODE_ID','DISBURSAL_DATE','PERFORM_CNS_SCORE_DESCRIPTION'])

In [25]:
df.dtypes

DISBURSED_AMOUNT                         int64
ASSET_COST                               int64
LTV                                    float64
DATE_OF_BIRTH                           object
EMPLOYMENT_TYPE                         object
MOBILENO_AVL_FLAG                        int64
AADHAR_FLAG                              int64
PAN_FLAG                                 int64
VOTERID_FLAG                             int64
DRIVING_FLAG                             int64
PASSPORT_FLAG                            int64
PERFORM_CNS_SCORE                        int64
PRI_NO_OF_ACCTS                          int64
PRI_ACTIVE_ACCTS                         int64
PRI_OVERDUE_ACCTS                        int64
PRI_CURRENT_BALANCE                      int64
PRI_SANCTIONED_AMOUNT                    int64
PRI_DISBURSED_AMOUNT                     int64
SEC_NO_OF_ACCTS                          int64
SEC_ACTIVE_ACCTS                         int64
SEC_OVERDUE_ACCTS                        int64
SEC_CURRENT_BALANCE                      int64
SEC_SANCTIONED_AMOUNT                    int64
SEC_DISBURSED_AMOUNT                     int64
PRIMARY_INSTAL_AMT                       int64
SEC_INSTAL_AMT                           int64
NEW_ACCTS_IN_LAST_SIX_MONTHS             int64
DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS      int64
AVERAGE_ACCT_AGE                        object
CREDIT_HISTORY_LENGTH                   object
NO_OF_INQUIRIES                          int64
LOAN_DEFAULT                             int64
dtype: object

In [26]:
df.isnull().sum()

DISBURSED_AMOUNT                         0
ASSET_COST                               0
LTV                                      0
DATE_OF_BIRTH                            0
EMPLOYMENT_TYPE                        144
MOBILENO_AVL_FLAG                        0
AADHAR_FLAG                              0
PAN_FLAG                                 0
VOTERID_FLAG                             0
DRIVING_FLAG                             0
PASSPORT_FLAG                            0
PERFORM_CNS_SCORE                        0
PRI_NO_OF_ACCTS                          0
PRI_ACTIVE_ACCTS                         0
PRI_OVERDUE_ACCTS                        0
PRI_CURRENT_BALANCE                      0
PRI_SANCTIONED_AMOUNT                    0
PRI_DISBURSED_AMOUNT                     0
SEC_NO_OF_ACCTS                          0
SEC_ACTIVE_ACCTS                         0
SEC_OVERDUE_ACCTS                        0
SEC_CURRENT_BALANCE                      0
SEC_SANCTIONED_AMOUNT                    0
SEC_DISBURSED_AMOUNT                     0
PRIMARY_INSTAL_AMT                       0
SEC_INSTAL_AMT                           0
NEW_ACCTS_IN_LAST_SIX_MONTHS             0
DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS      0
AVERAGE_ACCT_AGE                         0
CREDIT_HISTORY_LENGTH                    0
NO_OF_INQUIRIES                          0
LOAN_DEFAULT                             0
dtype: int64

In [27]:
df['EMPLOYMENT_TYPE'] = df['EMPLOYMENT_TYPE'].fillna('Unknown')

In [28]:
df = pd.get_dummies(df, columns=['EMPLOYMENT_TYPE'], dtype=int)

AI CODE

In [29]:
def convert_to_months(age_string):
    years = int(age_string.split('yrs')[0])
    months = int(age_string.split(' ')[1].replace('mon',''))
    return years*12 + months

In [30]:
df["AVERAGE_ACCT_AGE"] = df["AVERAGE_ACCT_AGE"].apply(convert_to_months)
df["CREDIT_HISTORY_LENGTH"] = df["CREDIT_HISTORY_LENGTH"].apply(convert_to_months)

In [35]:
df["DATE_OF_BIRTH"] = pd.to_datetime(df["DATE_OF_BIRTH"], dayfirst=True)
df["AGE"] = ((pd.Timestamp.today() - df["DATE_OF_BIRTH"]).dt.days / 365).round().astype(int)

In [36]:
df.dtypes

DISBURSED_AMOUNT                                int64
ASSET_COST                                      int64
LTV                                           float64
DATE_OF_BIRTH                          datetime64[ns]
MOBILENO_AVL_FLAG                               int64
AADHAR_FLAG                                     int64
PAN_FLAG                                        int64
VOTERID_FLAG                                    int64
DRIVING_FLAG                                    int64
PASSPORT_FLAG                                   int64
PERFORM_CNS_SCORE                               int64
PRI_NO_OF_ACCTS                                 int64
PRI_ACTIVE_ACCTS                                int64
PRI_OVERDUE_ACCTS                               int64
PRI_CURRENT_BALANCE                             int64
PRI_SANCTIONED_AMOUNT                           int64
PRI_DISBURSED_AMOUNT                            int64
SEC_NO_OF_ACCTS                                 int64
SEC_ACTIVE_ACCTS                                int64
SEC_OVERDUE_ACCTS                               int64
SEC_CURRENT_BALANCE                             int64
SEC_SANCTIONED_AMOUNT                           int64
SEC_DISBURSED_AMOUNT                            int64
PRIMARY_INSTAL_AMT                              int64
SEC_INSTAL_AMT                                  int64
NEW_ACCTS_IN_LAST_SIX_MONTHS                    int64
DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS             int64
AVERAGE_ACCT_AGE                                int64
CREDIT_HISTORY_LENGTH                           int64
NO_OF_INQUIRIES                                 int64
LOAN_DEFAULT                                    int64
EMPLOYMENT_TYPE_Salaried                        int64
EMPLOYMENT_TYPE_Self employed                   int64
EMPLOYMENT_TYPE_Unknown                         int64
AGE                                             int64
dtype: object

In [32]:
df.describe()

,DISBURSED_AMOUNT,ASSET_COST,LTV,MOBILENO_AVL_FLAG,AADHAR_FLAG,PAN_FLAG,VOTERID_FLAG,DRIVING_FLAG,PASSPORT_FLAG,PERFORM_CNS_SCORE,...,SEC_INSTAL_AMT,NEW_ACCTS_IN_LAST_SIX_MONTHS,DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS,AVERAGE_ACCT_AGE,CREDIT_HISTORY_LENGTH,NO_OF_INQUIRIES,LOAN_DEFAULT,EMPLOYMENT_TYPE_Salaried,EMPLOYMENT_TYPE_Self employed,EMPLOYMENT_TYPE_Unknown
count,5000.000000,5000.000000,5000.000000,5000.0,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,...,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,52618.059800,75361.666000,72.859102,1.0,0.705400,0.097800,0.268400,0.030800,0.001600,261.070000,...,259.952800,0.314800,0.08860,8.602200,14.772000,0.19120,0.224400,0.451800,0.519400,0.028800
std,11356.022842,16511.840509,11.417345,0.0,0.455908,0.297074,0.443171,0.172793,0.039972,332.599411,...,7914.561715,0.857816,0.35941,15.310272,26.939183,0.76887,0.417228,0.497721,0.499673,0.167261
min,13990.000000,39605.000000,17.050000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,46176.750000,65831.000000,66.837500,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
50%,52603.000000,70764.000000,74.850000,1.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000
75%,58585.000000,78800.250000,80.610000,1.0,1.000000,0.000000,1.000000,0.000000,0.000000,651.000000,...,0.000000,0.000000,0.00000,12.000000,21.000000,0.00000,0.000000,1.000000,1.000000,0.000000
max,151143.000000,225100.000000,94.990000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,879.000000,...,504063.000000,14.000000,5.00000,154.000000,296.000000,18.00000,1.000000,1.000000,1.000000,1.000000

In [42]:
df.columns = df.columns.str.replace(" ", "_")

In [43]:
corr = df.corr()

corr["DISBURSED_AMOUNT"].sort_values(ascending=False)

DISBURSED_AMOUNT                       1.000000
ASSET_COST                             0.696747
LTV                                    0.438774
LOAN_DEFAULT                           0.105253
DATE_OF_BIRTH                          0.066182
EMPLOYMENT_TYPE_Unknown                0.065989
EMPLOYMENT_TYPE_Salaried               0.061016
VOTERID_FLAG                           0.056148
DELINQUENT_ACCTS_IN_LAST_SIX_MONTHS    0.052429
PRI_NO_OF_ACCTS                        0.036486
NEW_ACCTS_IN_LAST_SIX_MONTHS           0.035209
PRI_OVERDUE_ACCTS                      0.029049
PRI_ACTIVE_ACCTS                       0.026774
PRI_CURRENT_BALANCE                    0.022317
NO_OF_INQUIRIES                        0.020236
PRI_DISBURSED_AMOUNT                   0.019303
PRI_SANCTIONED_AMOUNT                  0.019143
SEC_INSTAL_AMT                         0.011213
SEC_NO_OF_ACCTS                        0.010816
DRIVING_FLAG                           0.009953
SEC_ACTIVE_ACCTS                       0.007609
SEC_DISBURSED_AMOUNT                   0.002329
SEC_SANCTIONED_AMOUNT                  0.002286
SEC_CURRENT_BALANCE                    0.000997
PAN_FLAG                              -0.000170
SEC_OVERDUE_ACCTS                     -0.001195
PRIMARY_INSTAL_AMT                    -0.004567
PASSPORT_FLAG                         -0.007952
CREDIT_HISTORY_LENGTH                 -0.014599
AVERAGE_ACCT_AGE                      -0.028783
PERFORM_CNS_SCORE                     -0.032883
AADHAR_FLAG                           -0.065154
AGE                                   -0.067368
EMPLOYMENT_TYPE_Self_employed         -0.082867
MOBILENO_AVL_FLAG                           NaN
Name: DISBURSED_AMOUNT, dtype: float64

In [44]:
model_1 = sm.ols(
'DISBURSED_AMOUNT ~ ASSET_COST + LTV + AGE + PERFORM_CNS_SCORE + CREDIT_HISTORY_LENGTH + AVERAGE_ACCT_AGE + PRI_ACTIVE_ACCTS + PRI_CURRENT_BALANCE + EMPLOYMENT_TYPE_Salaried + EMPLOYMENT_TYPE_Self_employed',
data=df
).fit()

print(model_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       DISBURSED_AMOUNT   R-squared:                       0.972
Model:                            OLS   Adj. R-squared:                  0.971
Method:                 Least Squares   F-statistic:                 1.701e+04
Date:                Wed, 11 Mar 2026   Prob (F-statistic):               0.00
Time:                        11:24:32   Log-Likelihood:                -44887.
No. Observations:                5000   AIC:                         8.980e+04
Df Residuals:                    4989   BIC:                         8.987e+04
Df Model:                          10
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                     -4.844e+04    327.126   -148.064      0.000   -4.91e+04   -4.78e+04
ASSET_COST                        0.6401      0.002    365.359      0.000       0.637       0.643
LTV                             729.1802      2.546    286.432      0.000     724.189     734.171
AGE                              -0.1130      2.919     -0.039      0.969      -5.835       5.609
PERFORM_CNS_SCORE                 0.0169      0.105      0.162      0.871      -0.188       0.222
CREDIT_HISTORY_LENGTH            -3.8366      2.162     -1.774      0.076      -8.076       0.402
AVERAGE_ACCT_AGE                  5.3060      3.558      1.491      0.136      -1.670      12.282
PRI_ACTIVE_ACCTS                 16.0364     21.121      0.759      0.448     -25.370      57.442
PRI_CURRENT_BALANCE            7.604e-05   4.59e-05      1.657      0.098   -1.39e-05       0.000
EMPLOYMENT_TYPE_Salaried       -159.0665    167.060     -0.952      0.341    -486.578     168.445
EMPLOYMENT_TYPE_Self_employed  -480.0888    167.116     -2.873      0.004    -807.710    -152.468
==============================================================================
Omnibus:                     2562.740   Durbin-Watson:                   1.709
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            46856.240
Skew:                          -2.020   Prob(JB):                         0.00
Kurtosis:                      17.442   Cond. No.                     8.44e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.44e+06. This might indicate that there are
strong multicollinearity or other numerical problems.